// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroDatabase;

#nullable disable

namespace SuperHeroCrud.Migrations
{
    [DbContext(typeof(SHDatabase))]
    [Migration("20241211212540_newTablesDatabase")]
    partial class newTablesDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SuperHeroDatabase.HeroesSuperPowers", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuperPowerId")
                        .HasColumnType("TEXT");

                    b.HasKey("HeroId", "SuperPowerId");

                    b.HasIndex("SuperPowerId");

                    b.ToTable("HeroesSuperPowersDB");
                });

            modelBuilder.Entity("SuperHeroDatabase.SuperHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("HeroName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SuperHeroDB");
                });

            modelBuilder.Entity("SuperHeroDatabase.SuperPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SuperPowerDB");
                });

            modelBuilder.Entity("SuperHeroDatabase.HeroesSuperPowers", b =>
                {
                    b.HasOne("SuperHeroDatabase.SuperHero", "Hero")
                        .WithMany("HeroesSuperPowers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperHeroDatabase.SuperPower", "SuperPower")
                        .WithMany("HeroesSuperPowers")
                        .HasForeignKey("SuperPowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("SuperPower");
                });

            modelBuilder.Entity("SuperHeroDatabase.SuperHero", b =>
                {
                    b.Navigation("HeroesSuperPowers");
                });

            modelBuilder.Entity("SuperHeroDatabase.SuperPower", b =>
                {
                    b.Navigation("HeroesSuperPowers");
                });
#pragma warning restore 612, 618
        }
    }
}
